const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand(); const API=window.OVOZ_API||'http://localhost:8000'; let S={}; const $=x=>document.getElementById(x);
async function api(path,opt={}){let h={'Content-Type':'application/json',...(opt.headers||{})};if(tg?.initData)h['X-Telegram-Init-Data']=tg.initData;let r=await fetch(API+path,{...opt,headers:h});let d=await r.json();if(!r.ok)throw Error(d.detail||'Xatolik');return d}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function init(){try{S=await api('/api/me');$('user').textContent=S.user.first_name||'Telegram User';$('stars').textContent=S.stars;home()}catch(e){$('user').textContent='Demo / Backendni ulang';home();}setTimeout(()=>{$('splash').classList.add('hidden');$('app').classList.remove('hidden')},900)}
function shell(html){$('content').innerHTML=html}
function home(){shell(`<div class="card hero"><div class="muted">Sizning balansingiz</div><div class="big">⭐ ${S.stars||0}</div><button class="primary" onclick="spin()">✨ BEPUL AYLANtirish</button><p class="muted">Har 24 soatda 1 marta. Qolgan vaqt: ${S.freeSpinAvailable?'tayyor':'24 soatlik limit'}</p></div><div class="card"><h3>Tezkor</h3><div class="row"><span>👥 Referral</span><button onclick="page('ref')">Ochish</button></div><div class="row"><span>📋 Vazifalar</span><button onclick="page('tasks')">Ochish</button></div><div class="row"><span>🏆 TOP-20</span><button onclick="ranking()">Ko‘rish</button></div></div>`)}
async function spin(){try{let d=await api('/api/spin/free',{method:'POST'});S.stars+=d.reward;$('stars').textContent=S.stars;modal('🎉 TABRIKLAYMIZ!',`Siz ${d.reward} ⭐ yutdingiz!`)}catch(e){alert(e.message)}}
async function page(p){if(p==='home')return home();if(p==='game')return shell(`<div class="card"><h2>🎮 Game</h2><p class="muted">Bu versiyada pul tikish yoki Stars evaziga tasodifiy yutuq olish mexanizmi yo‘q. Bepul promo o‘yin ishlaydi.</p><button class="primary" onclick="spin()">BEPUL SPIN</button></div>`);if(p==='tasks'){let d=await api('/api/tasks');shell(`<div class="card"><h2>📋 Vazifalar</h2>${d.tasks.map(t=>`<div class="row"><span>${esc(t.title)}<br><small class="muted">+${t.reward} ⭐</small></span><button onclick="claim('${t.id}')">${t.status==='completed'?'Olindi':'Claim'}</button></div>`).join('')}</div>`);return}if(p==='ref'){let d=await api('/api/referral');shell(`<div class="card"><h2>👥 Referral</h2><div class="row"><span>Taklif mukofoti</span><b>+${d.reward} ⭐</b></div><div class="row"><span>Taklif qilingan</span><b>${d.count}</b></div><input id="ref" value="${d.link}" readonly><button class="primary" onclick="navigator.clipboard.writeText($('ref').value);alert('Nusxalandi')">LINKNI NUSXALASH</button><br><br><button class="primary" onclick="tg?.openTelegramLink?.('https://t.me/share/url?url='+encodeURIComponent('${d.link}'))">DO‘STLARNI TAKLIF QILISH</button></div>`);return}if(p==='profile'){shell(`<div class="card"><h2>👤 Profil</h2><div class="row"><span>ID</span><b>${S.user?.telegram_id||0}</b></div><div class="row"><span>Stars</span><b>${S.stars} ⭐</b></div><div class="row"><span>Referral</span><b>${S.referrals||0}</b></div><div class="row"><span>TOP</span><b>#${S.rank||'-'}</b></div></div><div class="card"><h3>💸 Yechib olish</h3><p class="muted">Minimum 5 Stars. 15 / 25 / 50 / 100 yoki o‘zingiz kiritgan miqdor.</p><input id="wa" type="number" min="5" placeholder="Miqdor"><button class="primary" onclick="withdraw()">SO‘ROV YUBORISH</button></div><div class="card"><button class="primary" onclick="historyPage()">📜 Tarix</button></div>`)}
async function claim(id){try{let d=await api('/api/tasks/'+id+'/claim',{method:'POST'});if(d.ok){S.stars+=d.reward;$('stars').textContent=S.stars;alert('+'+d.reward+' Stars')}else alert(d.message);page('tasks')}catch(e){alert(e.message)}}
async function ranking(){let d=await api('/api/ranking');shell(`<div class="card"><h2>🏆 TOP-20</h2>${d.items.map((x,i)=>`<div class="row"><span>#${i+1} ${esc(x.first_name||x.username||'User')}</span><b>${x.stars} ⭐</b></div>`).join('')}</div>`)}
async function historyPage(){let d=await api('/api/history');shell(`<div class="card"><h2>📜 Tarix</h2>${d.items.map(x=>`<div class="row"><span>${esc(x.type)}<br><small class="muted">${new Date(x.created_at).toLocaleString()}</small></span><b>${x.amount>0?'+':''}${x.amount} ⭐</b></div>`).join('')||'<p class="muted">Tarix bo‘sh</p>'}</div>`)}
async function withdraw(){try{let a=Number($('wa').value);await api('/api/withdraw',{method:'POST',body:JSON.stringify({amount:a})});S.stars-=a;$('stars').textContent=S.stars;alert('So‘rov adminlarga yuborildi')}catch(e){alert(e.message)}}
function modal(title,text){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div><h2>${title}</h2><p>${text}</p><button class="primary" onclick="this.parentElement.parentElement.remove()">OK</button></div>`;document.body.appendChild(m)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.page));init();
